name: pandora_mitm
description: A mitmproxy Remote Interceptions client that can analyse and modify Pandora JSON API messages.
version: 0.1.0
homepage: https://github.com/EpimetheusMusicPlayer/pandora_mitm

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  logging: ^1.0.2
  mitmproxy_ri_client:
    git:
      url: 'https://github.com/hacker1024/mitmproxy_ri_client.dart.git'
      ref: 8b23a897d4d39a09faa50b362a27d8fcc816ce3d
  iapetus:
    git:
      url: 'https://github.com/EpimetheusMusicPlayer/Iapetus.git'
      ref: 3a0f5cabdf85b7aa4817870ed9cb90c006a30346
  freezed_annotation: ^2.0.3

dev_dependencies:
  lint: ^1.8.2
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
