name: pandora_mitm_extra
description: Extra functionality for pandora_mitm.
version: 0.1.0
homepage: https://github.com/EpimetheusMusicPlayer/pandora_mitm/tree/master/pandora_mitm_extra

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  pandora_mitm:
    path: ../pandora_mitm
  iapetus:
    path: ../iapetus
  iapetus_meta:
    path: ../iapetus_meta/iapetus_meta
  markdown: ^5.0.0

dev_dependencies:
  lint: ^1.8.2

dependency_overrides:
  iapetus:
    path: ../iapetus
