name: CD

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          architecture: x64
      - run: flutter config --suppress-analytics --no-analytics --enable-web --enable-macos-desktop
      - run: |
          flutter pub global activate melos
          melos bootstrap

      # Generate version names
      - name: Create version names
        id: versions
        run: |
          cd pandora_mitm_gui
          echo "::set-output name=gui_version::$(grep 'version:' pubspec.yaml | awk '{ print $2 }' | cut -d'+' -f 1)b"
          cd ..
          cd pandora_mitm_cli
          echo "::set-output name=cli_version::$(grep 'version:' pubspec.yaml | awk '{ print $2 }' | cut -d'+' -f 1)b"
          cd ..

      # -- Build GUI --

      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: pandora_mitm_gui
          targetBranch: gh-pages
          baseHref: ${{ github.event.repository.name }}
          webRenderer: canvaskit
          customArgs: --build-name=${{ steps.versions.outputs.gui_version }}

      - working-directory: pandora_mitm_gui
        run: |
          flutter build macos --release --build-name=${{ steps.versions.outputs.gui_version }}
          cd build/macos/Build/Products/Release
          brew install create-dmg
          create-dmg \
            --volname 'Pandora MITM' \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 96 \
            --icon 'Pandora MITM.app' 200 190 \
            --hide-extension 'Pandora MITM.app' \
            --app-drop-link 600 185 \
            'PandoraMITMv${{ steps.versions.outputs.gui_version }}.dmg' \
            'Pandora MITM.app'

      # -- Publish GUI --

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: gui-v${{ steps.versions.outputs.gui_version }}
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          tag: gui-v${{ steps.versions.outputs.gui_version }}
          prerelease: true
          name: [CD] Pandora MITM GUI v${{ steps.versions.outputs.gui_version }}
          body: This is an automatic prerelease build of the Pandora MITM GUI.
          artifacts: pandora_mitm_gui/build/macos/Build/Products/Release/PandoraMITMv${{ steps.versions.outputs.gui_version }}.dmg

